/* CREATING DATABASE(SCHEMA) */
CREATE DATABASE IF NOT EXISTS SALES;
CREATE SCHEMA IF NOT EXISTS SALES;
/* BOTH EXECUTES THE SAME RESULT*/

USE SALES;

CREATE TABLE SALES
(
	purchase_number INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    date_of_purchase DATE NOT NULL,
    customer_id INT,
    item_code VARCHAR(10) NOT NULL
);
    
CREATE TABLE CUSTOMERS
(
	customer_id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email_address VARCHAR(255),
    number_of_complaints int
);

/* BOTH SHOWS THE SAME TABLE SALES*/
SELECT * FROM SALES;
SELECT * FROM SALES.SALES;

